# Generated by Django 2.0.5 on 2018-05-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180518_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('text', models.TextField()),
                ('date', models.DateField(verbose_name='publish date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.NavOption')),
            ],
        ),
    ]
