# Generated by Django 2.0.5 on 2018-08-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='image name'),
        ),
    ]
