# Generated by Django 2.0.5 on 2018-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='navoption',
            name='icon',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='fa class name'),
        ),
    ]
