# Generated by Django 2.0.5 on 2018-08-23 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_navoption_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='display name')),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='navoption',
            name='icon',
        ),
        migrations.AddField(
            model_name='menuoption',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.NavOption'),
        ),
    ]
