# Generated by Django 2.0.5 on 2018-08-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180823_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='embed',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='embed url'),
        ),
        migrations.AddField(
            model_name='menuoption',
            name='perm_req',
            field=models.IntegerField(default=1, verbose_name='permission level required'),
            preserve_default=False,
        ),
    ]
